### ISSUE TITLE
Norton Power Eraser detecting EZBlocker3 as malware. 

### ISSUE THREAD

**Issue by ghost** [OpenByteDev/EZBlocker3#3]
I use many second opinion antivirus and norton power eraser is detecting the application as a malware.

**Comment by OpenByteDev** [comment]
If you dont feel comfortable using my prebuilt executable you can just have a look at the source code and built it yourself.

If not I dont think I can really do something about that, because many anti virus applications just mark every unsigned rarely-seen app as harmful.

VirusTotal does not pick up anything as an example: https://www.virustotal.com/gui/url/7acd5a0592d49ce38d3da3b98c6ea749d745af1921d102247e7ef6712e77c3d7/detection

I would be interested if you have any idea to avoid being marked by antiviruses except paying to have the exe signed.
